spring:
  application:
    name: product-application
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:12088
      metric:
        charset: UTF-8
      eager: false

# server
server:
  port: 18081
  servlet:
    context-path: /product-api/



management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,prometheus
    metrics:
      enabled: true

swagger:
  enable: true
  title: 商品子系统
  description: 商品子系统
  version: 1.0.0
  base-package: cn.iocoder.mall.product.application.controller