spring:
  application:
    name: promotion-application
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:12088
      metric:
        charset: UTF-8
      eager: false

# server
server:
  port: 18085
  servlet:
    context-path: /promotion-api/

swagger:
  enable: true
  title: 促销子系统
  description: 促销子系统
  version: 1.0.0
  base-package: cn.iocoder.mall.promotion.application.controller


management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,prometheus
    metrics:
      enabled: true
